name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Deploy Backend
  deploy-backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd backend
        npm ci --production
        
    - name: Create deployment package
      run: |
        cd backend
        tar -czf ../backend-deployment.tar.gz .
        
    - name: Upload backend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-deployment
        path: backend-deployment.tar.gz
        retention-days: 30

  # Deploy Frontend (Web Demo)
  deploy-frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web demo
      run: |
        # Copy web demo files
        cp -r web-demo/* ./dist/
        cp -r mobile-web/* ./dist/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

  # Build Mobile App
  build-mobile:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './SAI-Fitness-Mobile/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd SAI-Fitness-Mobile
        npm ci
        
    - name: Install Expo CLI
      run: npm install -g @expo/cli
      
    - name: Build Expo app
      run: |
        cd SAI-Fitness-Mobile
        npx expo export --platform all
        
    - name: Upload mobile build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mobile-build
        path: SAI-Fitness-Mobile/dist/
        retention-days: 30

  # Notify deployment status
  notify:
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend, build-mobile]
    if: always()
    
    steps:
    - name: Notify deployment status
      run: |
        if [ "${{ needs.deploy-backend.result }}" == "success" ] && [ "${{ needs.deploy-frontend.result }}" == "success" ] && [ "${{ needs.build-mobile.result }}" == "success" ]; then
          echo "✅ All deployments successful!"
        else
          echo "❌ Some deployments failed"
          exit 1
        fi
